name: CI

on: [push]

jobs:
  build:
    runs-on: macos
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Update Dependencies
      run: carthage update --cache-builds --platform iOS 
    - name: Build the App
      run: |
        xcodebuild clean build CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO
        
